#! /usr/bin/ruby 

module Command

  def commandResponse
    oper, para = ARGV[0], ARGV[1]
    if oper == "init" && para == nil
      $file = PRWB.new
    elsif oper == "add" && para == "slide" #添加新的slide界面
      $file.addslide
    elsif oper == "add" && para == "step" #添加新的step界面
      $file.addstep
    elsif oper == "edit" && para != nil
      $file.edit para
    elsif oper == "delete" && para != nil
      $file.delete para
    else
    puts "You didn't input the correct command lines"
    puts "Add new presentation file using 'prwb init'"
    puts "Add a new slide view in the presentation file using 'prwb add slide'"
    puts "Add a new step view in the presentation file using 'prwb add step'"
    puts "Edit a view in the presentation file using 'prwb edit view-id'"
    puts "Delete a view in the presentation file using 'prwb delete view-id'"
    end
  end

  module_function :commandResponse
end


class PRWB
  attr_reader :template
  def initialize
    File.open "presentation.html", "w" do |file|
      file.puts self.template
    end
  end
  def template
    @template = %Q{

<html>
<head>
    <title>My Presentation</title>
    <meta charset="utf-8">
    <link href="../css/webpresent.css" rel="stylesheet">
    <link href="../css/theme.css" rel="stylesheet">
    <link rel="stylesheet" href="../css/xcode.css">
    <script src="../js/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body class="impress-not-supported">
    <div class="fallback-message">
        <h1>Sorry, but the browser you're currently using is not support here...</h1>
        <h1>Try another browsers like <cite>Chrome</cite>, <cite>Firefox</cite>, or <cite>Safari</cite></h1>
    </div>
    <div id="impress">
        
    </div>
    <script src="../js/impress.js"></script>
    <script src="../js/showdown.js"></script>
    <script>impress().init();</script>
    <script>
        var conv = new Showdown.converter();
    </script>

</body>
</html>
    

    }
  end
end

Command.commandResponse
puts $file.class
